package api

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strconv"
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"hoardqr/internal/store"
)

type LocationsHandler struct {
	pool *pgxpool.Pool
	q    *store.Queries
}

func NewLocationsHandler(pool *pgxpool.Pool) *LocationsHandler {
	return &LocationsHandler{pool: pool, q: store.New(pool)}
}

func (h *LocationsHandler) Routes(r chi.Router) {
	r.Get("/", h.list)
	r.Post("/", h.create)
	r.Get("/{id}", h.get)
	r.Get("/{id}/contents", h.contents)
	r.Patch("/{id}", h.update)
	r.Delete("/{id}", h.delete)
}

func parseIDParam(r *http.Request) (int64, error) {
	return strconv.ParseInt(chi.URLParam(r, "id"), 10, 64)
}

// breadcrumbDTO fetches and shapes a location's root-to-leaf path — shared
// by every handler below that needs one alongside the location/item itself.
func (h *LocationsHandler) breadcrumbDTO(ctx context.Context, locationID int64) ([]BreadcrumbEntryDTO, error) {
	rows, err := h.q.LocationBreadcrumb(ctx, locationID)
	if err != nil {
		return nil, err
	}
	out := make([]BreadcrumbEntryDTO, len(rows))
	for i, row := range rows {
		out[i] = BreadcrumbEntryDTO{ID: row.ID, Name: row.Name}
	}
	return out, nil
}

// GET /api/locations?parent_id=
func (h *LocationsHandler) list(w http.ResponseWriter, r *http.Request) {
	var parentID *int64
	if raw := r.URL.Query().Get("parent_id"); raw != "" {
		id, err := strconv.ParseInt(raw, 10, 64)
		if err != nil {
			writeError(w, http.StatusBadRequest, "parent_id must be an integer")
			return
		}
		parentID = &id
	}
	locations, err := h.q.GetLocationsByParent(r.Context(), parentID)
	if err != nil {
		serverError(w, r, err)
		return
	}
	writeJSON(w, http.StatusOK, toLocationDTOs(locations))
}

// GET /api/locations/:id
func (h *LocationsHandler) get(w http.ResponseWriter, r *http.Request) {
	id, err := parseIDParam(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid id")
		return
	}
	location, err := h.q.GetLocationByID(r.Context(), id)
	if isNoRows(err) {
		notFound(w, "location")
		return
	}
	if err != nil {
		serverError(w, r, err)
		return
	}
	breadcrumb, err := h.breadcrumbDTO(r.Context(), id)
	if err != nil {
		serverError(w, r, err)
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"location":   toLocationDTO(location),
		"breadcrumb": breadcrumb,
	})
}

// GET /api/locations/:id/contents — recursive: everything under it (§3).
func (h *LocationsHandler) contents(w http.ResponseWriter, r *http.Request) {
	id, err := parseIDParam(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid id")
		return
	}
	location, err := h.q.GetLocationByID(r.Context(), id)
	if isNoRows(err) {
		notFound(w, "location")
		return
	}
	if err != nil {
		serverError(w, r, err)
		return
	}
	breadcrumb, err := h.breadcrumbDTO(r.Context(), id)
	if err != nil {
		serverError(w, r, err)
		return
	}
	descendantIDs, err := h.q.DescendantLocationIDs(r.Context(), id)
	if err != nil {
		serverError(w, r, err)
		return
	}
	rows, err := h.q.ListItemsByLocationIDs(r.Context(), descendantIDs)
	if err != nil {
		serverError(w, r, err)
		return
	}
	items := make([]ItemDTO, len(rows))
	for i, row := range rows {
		items[i] = toItemDTOFromContentsRow(row)
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"location":   toLocationDTO(location),
		"breadcrumb": breadcrumb,
		"items":      items,
	})
}

type createLocationRequest struct {
	Name     string  `json:"name"`
	ParentID *int64  `json:"parent_id"`
	QrToken  *string `json:"qr_token"`
	PhotoURL *string `json:"photo_url"`
	Notes    *string `json:"notes"`
	IsShared *bool   `json:"is_shared"`
}

// POST /api/locations
func (h *LocationsHandler) create(w http.ResponseWriter, r *http.Request) {
	var req createLocationRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}
	if strings.TrimSpace(req.Name) == "" {
		writeError(w, http.StatusBadRequest, "name is required")
		return
	}

	isShared := true
	if req.IsShared != nil {
		isShared = *req.IsShared
	}

	// A caller-supplied qr_token (adopted retail barcode, or the scanned code
	// from /scan's "create here" outcome) that collides is a real conflict —
	// return 409. A collision on an auto-generated code is "a non-event, not
	// something to design around" (§4): retry a few times before giving up,
	// since the caller never saw the value that collided.
	autoGenerated := req.QrToken == nil
	qrToken := ""
	if req.QrToken != nil {
		qrToken = *req.QrToken
	}

	var location store.Location
	var err error
	for attempt := 0; ; attempt++ {
		if autoGenerated {
			qrToken = generatePlainTextCode()
		}
		location, err = h.q.InsertLocation(r.Context(), store.InsertLocationParams{
			ParentID: req.ParentID,
			OwnerID:  nil, // no auth yet (Phase 3 step 5) — every row is ownerless until then
			IsShared: isShared,
			Name:     req.Name,
			QrToken:  qrToken,
			PhotoUrl: req.PhotoURL,
			Notes:    req.Notes,
		})
		if err == nil {
			break
		}
		if !pgConflict(err) {
			serverError(w, r, err)
			return
		}
		if !autoGenerated || attempt >= 5 {
			writeError(w, http.StatusConflict, fmt.Sprintf("qr_token %q already in use", qrToken))
			return
		}
	}
	writeJSON(w, http.StatusCreated, toLocationDTO(location))
}

// PATCH /api/locations/:id — rename, move, edit code, toggle is_shared (§9).
// Hand-written rather than sqlc-generated: any subset of columns may be
// present, and a provided `parent_id: null` (make this a root location) must
// be distinguishable from an absent parent_id (leave unchanged) — a
// COALESCE-based static query can't tell those apart, so this builds the SET
// clause from whichever keys actually appear in the JSON body.
func (h *LocationsHandler) update(w http.ResponseWriter, r *http.Request) {
	id, err := parseIDParam(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid id")
		return
	}

	var fields map[string]json.RawMessage
	if err := json.NewDecoder(r.Body).Decode(&fields); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}

	set := map[string]any{}
	for key, raw := range fields {
		switch key {
		case "name":
			var v string
			if err := json.Unmarshal(raw, &v); err != nil {
				writeError(w, http.StatusBadRequest, "name must be a string")
				return
			}
			set["name"] = v
		case "parent_id":
			var v *int64
			if err := json.Unmarshal(raw, &v); err != nil {
				writeError(w, http.StatusBadRequest, "parent_id must be an integer or null")
				return
			}
			set["parent_id"] = v
		case "qr_token":
			var v string
			if err := json.Unmarshal(raw, &v); err != nil {
				writeError(w, http.StatusBadRequest, "qr_token must be a string")
				return
			}
			set["qr_token"] = v
		case "photo_url":
			var v *string
			if err := json.Unmarshal(raw, &v); err != nil {
				writeError(w, http.StatusBadRequest, "photo_url must be a string or null")
				return
			}
			set["photo_url"] = v
		case "notes":
			var v *string
			if err := json.Unmarshal(raw, &v); err != nil {
				writeError(w, http.StatusBadRequest, "notes must be a string or null")
				return
			}
			set["notes"] = v
		case "is_shared":
			var v bool
			if err := json.Unmarshal(raw, &v); err != nil {
				writeError(w, http.StatusBadRequest, "is_shared must be a boolean")
				return
			}
			set["is_shared"] = v
		}
	}
	if len(set) == 0 {
		writeError(w, http.StatusBadRequest, "no updatable fields provided")
		return
	}

	if token, ok := set["qr_token"].(string); ok {
		inUse, err := h.q.LocationQRTokenInUse(r.Context(), store.LocationQRTokenInUseParams{QrToken: token, ID: id})
		if err != nil {
			serverError(w, r, err)
			return
		}
		if inUse {
			writeError(w, http.StatusConflict, fmt.Sprintf("qr_token %q already in use", token))
			return
		}
	}

	query, args := buildUpdateQuery("locations", id, set)
	if _, err := h.pool.Exec(r.Context(), query, args...); err != nil {
		if pgConflict(err) {
			writeError(w, http.StatusConflict, "qr_token already in use")
			return
		}
		serverError(w, r, err)
		return
	}

	location, err := h.q.GetLocationByID(r.Context(), id)
	if isNoRows(err) {
		notFound(w, "location")
		return
	}
	if err != nil {
		serverError(w, r, err)
		return
	}
	writeJSON(w, http.StatusOK, toLocationDTO(location))
}

// DELETE /api/locations/:id?force= (§3). Child locations always become
// root-level automatically (the FK's ON DELETE SET NULL fires as part of the
// DELETE below) — never blocked, never forced. The only case requiring
// force=true is a root location that still directly holds items: nowhere to
// promote them to.
//
// Runs as one transaction: promoting (or force-deleting) the direct items
// and then deleting the location are two-to-three separate statements, and
// the force branch is destructive — if DeleteLocation failed after
// DeleteItemsAtLocation had already committed, those items would be gone
// for good with the location they were deleted from still sitting there.
// The read that decides which branch to take also happens inside the
// transaction, so a concurrent reparent/delete of the same location can't
// race between the check and the write.
func (h *LocationsHandler) delete(w http.ResponseWriter, r *http.Request) {
	id, err := parseIDParam(r)
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid id")
		return
	}
	force := r.URL.Query().Get("force") == "true"

	var status int
	var message string

	err = withTx(r.Context(), h.pool, func(tx pgx.Tx) error {
		q := store.New(tx)

		location, err := q.GetLocationByID(r.Context(), id)
		if isNoRows(err) {
			status, message = http.StatusNotFound, "location not found"
			return errHandled
		}
		if err != nil {
			return err
		}

		if location.ParentID != nil {
			if err := q.PromoteItemsToParent(r.Context(), store.PromoteItemsToParentParams{
				NewLocationID: *location.ParentID,
				OldLocationID: id,
			}); err != nil {
				return err
			}
		} else {
			count, err := q.CountDirectItemsAtLocation(r.Context(), id)
			if err != nil {
				return err
			}
			if count > 0 {
				if !force {
					status, message = http.StatusConflict,
						"location holds items directly and has no parent to promote them to — retry with force=true"
					return errHandled
				}
				if err := q.DeleteItemsAtLocation(r.Context(), id); err != nil {
					return err
				}
			}
		}

		// Same transaction as the promote-or-delete-items branch above — if
		// this fails, the items move/delete above rolls back with it instead
		// of being left committed with the location still sitting there.
		return q.DeleteLocation(r.Context(), id)
	})

	if errors.Is(err, errHandled) {
		writeError(w, status, message)
		return
	}
	if err != nil {
		serverError(w, r, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}
