// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (entity_type, entity_id, action, user_id, details)
VALUES ($1::text, $2::bigint, $3::text, $4::bigint, $5::jsonb)
`

type InsertAuditLogParams struct {
	EntityType string
	EntityID   int64
	Action     string
	UserID     *int64
	Details    []byte
}

// §3's audit_log table, first written to by the MCP move_item tool (§11).
// user_id is nullable and left NULL here, same as every other row in the
// app right now — there's no real user to attribute it to until auth
// exists (deferred indefinitely, see CLAUDE.md).
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.UserID,
		arg.Details,
	)
	return err
}
