// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countItems = `-- name: CountItems :one
SELECT count(*) FROM items
`

func (q *Queries) CountItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteItem = `-- name: DeleteItem :exec

DELETE FROM items WHERE id = $1
`

// Item PATCH is hand-written in internal/api/items.go, same reasoning as
// location PATCH — arbitrary subset of columns, nullable fields included.
func (q *Queries) DeleteItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const getItemByID = `-- name: GetItemByID :one

SELECT i.id, i.location_id, i.owner_id, i.is_shared, i.name, i.description, i.quantity, i.condition, i.qr_token, i.photo_url, i.purchase_date, i.purchase_price, i.receipt_url, i.custom_fields, i.created_at, i.updated_at, COALESCE(array_agg(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL), '{}')::text[] AS tags
FROM items i
LEFT JOIN item_tags it ON it.item_id = i.id
LEFT JOIN tags t ON t.id = it.tag_id
WHERE i.id = $1
GROUP BY i.id
`

type GetItemByIDRow struct {
	ID            int64
	LocationID    int64
	OwnerID       *int64
	IsShared      bool
	Name          string
	Description   *string
	Quantity      int32
	Condition     *string
	QrToken       string
	PhotoUrl      *string
	PurchaseDate  pgtype.Date
	PurchasePrice pgtype.Numeric
	ReceiptUrl    *string
	CustomFields  []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
}

// Every item-returning query aggregates item_tags/tags into a plain text[] —
// Item.tags on the frontend is a joined convenience field, not a items table
// column (see CLAUDE.md), so a plain `SELECT * FROM items` is never enough.
func (q *Queries) GetItemByID(ctx context.Context, id int64) (GetItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i GetItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.OwnerID,
		&i.IsShared,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Condition,
		&i.QrToken,
		&i.PhotoUrl,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.ReceiptUrl,
		&i.CustomFields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
	)
	return i, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name FROM tags WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTagByNameCI = `-- name: GetTagByNameCI :one
SELECT id, name FROM tags WHERE lower(name) = lower($1)
`

// Matches the mock createTag's case-insensitive idempotency (tags.name has
// no case-insensitive unique index — application-level check, same as mock).
func (q *Queries) GetTagByNameCI(ctx context.Context, lower string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByNameCI, lower)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertItem = `-- name: InsertItem :one
INSERT INTO items (
    location_id, owner_id, is_shared, name, description, quantity, condition,
    qr_token, photo_url, purchase_date, purchase_price, receipt_url, custom_fields
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, location_id, owner_id, is_shared, name, description, quantity, condition, qr_token, photo_url, purchase_date, purchase_price, receipt_url, custom_fields, created_at, updated_at
`

type InsertItemParams struct {
	LocationID    int64
	OwnerID       *int64
	IsShared      bool
	Name          string
	Description   *string
	Quantity      int32
	Condition     *string
	QrToken       string
	PhotoUrl      *string
	PurchaseDate  pgtype.Date
	PurchasePrice pgtype.Numeric
	ReceiptUrl    *string
	CustomFields  []byte
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, insertItem,
		arg.LocationID,
		arg.OwnerID,
		arg.IsShared,
		arg.Name,
		arg.Description,
		arg.Quantity,
		arg.Condition,
		arg.QrToken,
		arg.PhotoUrl,
		arg.PurchaseDate,
		arg.PurchasePrice,
		arg.ReceiptUrl,
		arg.CustomFields,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.OwnerID,
		&i.IsShared,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Condition,
		&i.QrToken,
		&i.PhotoUrl,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.ReceiptUrl,
		&i.CustomFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTag = `-- name: InsertTag :one
INSERT INTO tags (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) InsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, insertTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const itemExists = `-- name: ItemExists :one
SELECT EXISTS(SELECT 1 FROM items WHERE id = $1)
`

func (q *Queries) ItemExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, itemExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const linkItemTag = `-- name: LinkItemTag :exec
INSERT INTO item_tags (item_id, tag_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LinkItemTagParams struct {
	ItemID int64
	TagID  int64
}

func (q *Queries) LinkItemTag(ctx context.Context, arg LinkItemTagParams) error {
	_, err := q.db.Exec(ctx, linkItemTag, arg.ItemID, arg.TagID)
	return err
}

const listItems = `-- name: ListItems :many
SELECT i.id, i.location_id, i.owner_id, i.is_shared, i.name, i.description, i.quantity, i.condition, i.qr_token, i.photo_url, i.purchase_date, i.purchase_price, i.receipt_url, i.custom_fields, i.created_at, i.updated_at, COALESCE(array_agg(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL), '{}')::text[] AS tags
FROM items i
LEFT JOIN item_tags it ON it.item_id = i.id
LEFT JOIN tags t ON t.id = it.tag_id
WHERE ($1::bigint IS NULL OR i.location_id = $1)
  AND ($2::text IS NULL OR i.name ILIKE '%' || $2 || '%')
  AND (
    $3::text IS NULL OR EXISTS (
      SELECT 1 FROM item_tags it2
      JOIN tags t2 ON t2.id = it2.tag_id
      WHERE it2.item_id = i.id AND t2.name = $3
    )
  )
GROUP BY i.id
ORDER BY i.name
`

type ListItemsParams struct {
	LocationID *int64
	Q          *string
	Tag        *string
}

type ListItemsRow struct {
	ID            int64
	LocationID    int64
	OwnerID       *int64
	IsShared      bool
	Name          string
	Description   *string
	Quantity      int32
	Condition     *string
	QrToken       string
	PhotoUrl      *string
	PurchaseDate  pgtype.Date
	PurchasePrice pgtype.Numeric
	ReceiptUrl    *string
	CustomFields  []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
}

// location_id/q/tag are all optional filters (§9) — sqlc.narg + the
// "IS NULL OR ..." pattern lets one static query cover every combination.
func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems, arg.LocationID, arg.Q, arg.Tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsRow
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.OwnerID,
			&i.IsShared,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.Condition,
			&i.QrToken,
			&i.PhotoUrl,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.ReceiptUrl,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByLocationIDs = `-- name: ListItemsByLocationIDs :many
SELECT i.id, i.location_id, i.owner_id, i.is_shared, i.name, i.description, i.quantity, i.condition, i.qr_token, i.photo_url, i.purchase_date, i.purchase_price, i.receipt_url, i.custom_fields, i.created_at, i.updated_at, COALESCE(array_agg(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL), '{}')::text[] AS tags
FROM items i
LEFT JOIN item_tags it ON it.item_id = i.id
LEFT JOIN tags t ON t.id = it.tag_id
WHERE i.location_id = ANY($1::bigint[])
GROUP BY i.id
ORDER BY i.name
`

type ListItemsByLocationIDsRow struct {
	ID            int64
	LocationID    int64
	OwnerID       *int64
	IsShared      bool
	Name          string
	Description   *string
	Quantity      int32
	Condition     *string
	QrToken       string
	PhotoUrl      *string
	PurchaseDate  pgtype.Date
	PurchasePrice pgtype.Numeric
	ReceiptUrl    *string
	CustomFields  []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
}

// Backs GET /api/locations/:id/contents — location_ids is the recursive
// descendant set from DescendantLocationIDs.
func (q *Queries) ListItemsByLocationIDs(ctx context.Context, locationIds []int64) ([]ListItemsByLocationIDsRow, error) {
	rows, err := q.db.Query(ctx, listItemsByLocationIDs, locationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsByLocationIDsRow
	for rows.Next() {
		var i ListItemsByLocationIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.OwnerID,
			&i.IsShared,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.Condition,
			&i.QrToken,
			&i.PhotoUrl,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.ReceiptUrl,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentItems = `-- name: ListRecentItems :many
SELECT i.id, i.location_id, i.owner_id, i.is_shared, i.name, i.description, i.quantity, i.condition, i.qr_token, i.photo_url, i.purchase_date, i.purchase_price, i.receipt_url, i.custom_fields, i.created_at, i.updated_at, COALESCE(array_agg(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL), '{}')::text[] AS tags
FROM items i
LEFT JOIN item_tags it ON it.item_id = i.id
LEFT JOIN tags t ON t.id = it.tag_id
GROUP BY i.id
ORDER BY i.created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentItemsParams struct {
	Limit  int32
	Offset int32
}

type ListRecentItemsRow struct {
	ID            int64
	LocationID    int64
	OwnerID       *int64
	IsShared      bool
	Name          string
	Description   *string
	Quantity      int32
	Condition     *string
	QrToken       string
	PhotoUrl      *string
	PurchaseDate  pgtype.Date
	PurchasePrice pgtype.Numeric
	ReceiptUrl    *string
	CustomFields  []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
}

// Backs getRecentItems (not in §9 — see CLAUDE.md's "Mock API surface"
// notes): the dashboard's newest-first feed.
func (q *Queries) ListRecentItems(ctx context.Context, arg ListRecentItemsParams) ([]ListRecentItemsRow, error) {
	rows, err := q.db.Query(ctx, listRecentItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentItemsRow
	for rows.Next() {
		var i ListRecentItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.OwnerID,
			&i.IsShared,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.Condition,
			&i.QrToken,
			&i.PhotoUrl,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.ReceiptUrl,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name FROM tags ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceItemTags = `-- name: ReplaceItemTags :exec
DELETE FROM item_tags WHERE item_id = $1
`

func (q *Queries) ReplaceItemTags(ctx context.Context, itemID int64) error {
	_, err := q.db.Exec(ctx, replaceItemTags, itemID)
	return err
}

const tagNamesForItem = `-- name: TagNamesForItem :many
SELECT t.name FROM tags t
JOIN item_tags it ON it.tag_id = t.id
WHERE it.item_id = $1
ORDER BY t.name
`

func (q *Queries) TagNamesForItem(ctx context.Context, itemID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, tagNamesForItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
