// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countItems = `-- name: CountItems :one
SELECT count(*) FROM items
`

func (q *Queries) CountItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteItem = `-- name: DeleteItem :exec

DELETE FROM items WHERE id = $1
`

// Item PATCH is hand-written in internal/api/items.go, same reasoning as
// storage PATCH — arbitrary subset of columns, nullable fields included.
func (q *Queries) DeleteItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const findItemsByExactName = `-- name: FindItemsByExactName :many
SELECT id, storage_id, owner_id, is_shared, name, description, quantity, condition, qr_token, photo_url, purchase_date, purchase_price, receipt_url, custom_fields, created_at, updated_at FROM items WHERE lower(name) = lower($1::text)
`

// Exact (case-insensitive) match, deliberately not fuzzy — used by
// delete_item's strict resolver (internal/mcpserver), which must never act
// on an approximate match the way resolveItem's fuzzy matching does for
// every other tool. Item names aren't unique, so this can still return more
// than one row — the caller refuses on that, same tie-handling shape as
// resolveItem's fuzzy version.
func (q *Queries) FindItemsByExactName(ctx context.Context, name string) ([]Item, error) {
	rows, err := q.db.Query(ctx, findItemsByExactName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.StorageID,
			&i.OwnerID,
			&i.IsShared,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.Condition,
			&i.QrToken,
			&i.PhotoUrl,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.ReceiptUrl,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemByID = `-- name: GetItemByID :one

SELECT i.id, i.storage_id, i.owner_id, i.is_shared, i.name, i.description, i.quantity, i.condition, i.qr_token, i.photo_url, i.purchase_date, i.purchase_price, i.receipt_url, i.custom_fields, i.created_at, i.updated_at, COALESCE(array_agg(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL), '{}')::text[] AS tags
FROM items i
LEFT JOIN item_tags it ON it.item_id = i.id
LEFT JOIN tags t ON t.id = it.tag_id
WHERE i.id = $1
GROUP BY i.id
`

type GetItemByIDRow struct {
	ID            int64
	StorageID     int64
	OwnerID       *int64
	IsShared      bool
	Name          string
	Description   *string
	Quantity      int32
	Condition     *string
	QrToken       string
	PhotoUrl      *string
	PurchaseDate  pgtype.Date
	PurchasePrice pgtype.Numeric
	ReceiptUrl    *string
	CustomFields  []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
}

// Every item-returning query aggregates item_tags/tags into a plain text[] —
// Item.tags on the frontend is a joined convenience field, not a items table
// column (see CLAUDE.md), so a plain `SELECT * FROM items` is never enough.
func (q *Queries) GetItemByID(ctx context.Context, id int64) (GetItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i GetItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.StorageID,
		&i.OwnerID,
		&i.IsShared,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Condition,
		&i.QrToken,
		&i.PhotoUrl,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.ReceiptUrl,
		&i.CustomFields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
	)
	return i, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name FROM tags WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTagByNameCI = `-- name: GetTagByNameCI :one
SELECT id, name FROM tags WHERE lower(name) = lower($1)
`

// Matches the mock createTag's case-insensitive idempotency (tags.name has
// no case-insensitive unique index — application-level check, same as mock).
func (q *Queries) GetTagByNameCI(ctx context.Context, lower string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByNameCI, lower)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertItem = `-- name: InsertItem :one
INSERT INTO items (
    storage_id, owner_id, is_shared, name, description, quantity, condition,
    qr_token, photo_url, purchase_date, purchase_price, receipt_url, custom_fields
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, storage_id, owner_id, is_shared, name, description, quantity, condition, qr_token, photo_url, purchase_date, purchase_price, receipt_url, custom_fields, created_at, updated_at
`

type InsertItemParams struct {
	StorageID     int64
	OwnerID       *int64
	IsShared      bool
	Name          string
	Description   *string
	Quantity      int32
	Condition     *string
	QrToken       string
	PhotoUrl      *string
	PurchaseDate  pgtype.Date
	PurchasePrice pgtype.Numeric
	ReceiptUrl    *string
	CustomFields  []byte
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, insertItem,
		arg.StorageID,
		arg.OwnerID,
		arg.IsShared,
		arg.Name,
		arg.Description,
		arg.Quantity,
		arg.Condition,
		arg.QrToken,
		arg.PhotoUrl,
		arg.PurchaseDate,
		arg.PurchasePrice,
		arg.ReceiptUrl,
		arg.CustomFields,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.StorageID,
		&i.OwnerID,
		&i.IsShared,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Condition,
		&i.QrToken,
		&i.PhotoUrl,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.ReceiptUrl,
		&i.CustomFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTag = `-- name: InsertTag :one
INSERT INTO tags (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) InsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, insertTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const itemExists = `-- name: ItemExists :one
SELECT EXISTS(SELECT 1 FROM items WHERE id = $1)
`

func (q *Queries) ItemExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, itemExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const linkItemTag = `-- name: LinkItemTag :exec
INSERT INTO item_tags (item_id, tag_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LinkItemTagParams struct {
	ItemID int64
	TagID  int64
}

func (q *Queries) LinkItemTag(ctx context.Context, arg LinkItemTagParams) error {
	_, err := q.db.Exec(ctx, linkItemTag, arg.ItemID, arg.TagID)
	return err
}

const listItems = `-- name: ListItems :many
WITH params AS (
    SELECT replace(replace(replace($2::text, '\', '\\'), '%', '\%'), '_', '\_') AS q_escaped
)
SELECT i.id, i.storage_id, i.owner_id, i.is_shared, i.name, i.description, i.quantity, i.condition, i.qr_token, i.photo_url, i.purchase_date, i.purchase_price, i.receipt_url, i.custom_fields, i.created_at, i.updated_at, COALESCE(array_agg(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL), '{}')::text[] AS tags
FROM items i
LEFT JOIN item_tags it ON it.item_id = i.id
LEFT JOIN tags t ON t.id = it.tag_id
WHERE ($1::bigint IS NULL OR i.storage_id = $1)
  AND ($2::text IS NULL OR i.name ILIKE '%' || (SELECT q_escaped FROM params) || '%' ESCAPE '\')
  AND (
    $3::text IS NULL OR EXISTS (
      SELECT 1 FROM item_tags it2
      JOIN tags t2 ON t2.id = it2.tag_id
      WHERE it2.item_id = i.id AND t2.name = $3
    )
  )
GROUP BY i.id
ORDER BY i.name
`

type ListItemsParams struct {
	StorageID *int64
	Q         *string
	Tag       *string
}

type ListItemsRow struct {
	ID            int64
	StorageID     int64
	OwnerID       *int64
	IsShared      bool
	Name          string
	Description   *string
	Quantity      int32
	Condition     *string
	QrToken       string
	PhotoUrl      *string
	PurchaseDate  pgtype.Date
	PurchasePrice pgtype.Numeric
	ReceiptUrl    *string
	CustomFields  []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
}

// storage_id/q/tag are all optional filters (§9) — sqlc.narg + the
// "IS NULL OR ..." pattern lets one static query cover every combination.
// q is LIKE-escaped the same way search.sql's SearchSuggest already is
// (backslash doubled first, then % and _ escaped, matched with ESCAPE '\')
// so a literal "%" or "_" in a search term matches literally instead of
// acting as a wildcard — this query used to pass q straight into ILIKE
// unescaped (q=% matched every item; q=_amme_ matched "Hammer"). The
// params CTE mirrors search.sql's own naming for the same computation.
func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems, arg.StorageID, arg.Q, arg.Tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsRow
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.StorageID,
			&i.OwnerID,
			&i.IsShared,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.Condition,
			&i.QrToken,
			&i.PhotoUrl,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.ReceiptUrl,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByStorageIDs = `-- name: ListItemsByStorageIDs :many
SELECT i.id, i.storage_id, i.owner_id, i.is_shared, i.name, i.description, i.quantity, i.condition, i.qr_token, i.photo_url, i.purchase_date, i.purchase_price, i.receipt_url, i.custom_fields, i.created_at, i.updated_at, COALESCE(array_agg(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL), '{}')::text[] AS tags
FROM items i
LEFT JOIN item_tags it ON it.item_id = i.id
LEFT JOIN tags t ON t.id = it.tag_id
WHERE i.storage_id = ANY($1::bigint[])
GROUP BY i.id
ORDER BY i.name
`

type ListItemsByStorageIDsRow struct {
	ID            int64
	StorageID     int64
	OwnerID       *int64
	IsShared      bool
	Name          string
	Description   *string
	Quantity      int32
	Condition     *string
	QrToken       string
	PhotoUrl      *string
	PurchaseDate  pgtype.Date
	PurchasePrice pgtype.Numeric
	ReceiptUrl    *string
	CustomFields  []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
}

// Backs GET /api/storages/:id/contents — storage_ids is the recursive
// descendant set from DescendantStorageIDs.
func (q *Queries) ListItemsByStorageIDs(ctx context.Context, storageIds []int64) ([]ListItemsByStorageIDsRow, error) {
	rows, err := q.db.Query(ctx, listItemsByStorageIDs, storageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsByStorageIDsRow
	for rows.Next() {
		var i ListItemsByStorageIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.StorageID,
			&i.OwnerID,
			&i.IsShared,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.Condition,
			&i.QrToken,
			&i.PhotoUrl,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.ReceiptUrl,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentItems = `-- name: ListRecentItems :many
SELECT i.id, i.storage_id, i.owner_id, i.is_shared, i.name, i.description, i.quantity, i.condition, i.qr_token, i.photo_url, i.purchase_date, i.purchase_price, i.receipt_url, i.custom_fields, i.created_at, i.updated_at, COALESCE(array_agg(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL), '{}')::text[] AS tags
FROM items i
LEFT JOIN item_tags it ON it.item_id = i.id
LEFT JOIN tags t ON t.id = it.tag_id
GROUP BY i.id
ORDER BY i.created_at DESC
LIMIT $2::bigint OFFSET $1::bigint
`

type ListRecentItemsParams struct {
	PageOffset int64
	PageLimit  int64
}

type ListRecentItemsRow struct {
	ID            int64
	StorageID     int64
	OwnerID       *int64
	IsShared      bool
	Name          string
	Description   *string
	Quantity      int32
	Condition     *string
	QrToken       string
	PhotoUrl      *string
	PurchaseDate  pgtype.Date
	PurchasePrice pgtype.Numeric
	ReceiptUrl    *string
	CustomFields  []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
}

// Backs getRecentItems (not in §9 — see CLAUDE.md's "Mock API surface"
// notes): the dashboard's newest-first feed. limit/offset are explicitly
// ::bigint (not left to default inference) so the generated Go params are
// int64 — ItemsHandler.listRecent computes offset as int64 specifically to
// avoid an int32 overflow wrapping a large page/pageSize into a negative
// offset, which Postgres would then reject with a generic error instead of
// a clean 400.
func (q *Queries) ListRecentItems(ctx context.Context, arg ListRecentItemsParams) ([]ListRecentItemsRow, error) {
	rows, err := q.db.Query(ctx, listRecentItems, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentItemsRow
	for rows.Next() {
		var i ListRecentItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.StorageID,
			&i.OwnerID,
			&i.IsShared,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.Condition,
			&i.QrToken,
			&i.PhotoUrl,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.ReceiptUrl,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name FROM tags ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceItemTags = `-- name: ReplaceItemTags :exec
DELETE FROM item_tags WHERE item_id = $1
`

func (q *Queries) ReplaceItemTags(ctx context.Context, itemID int64) error {
	_, err := q.db.Exec(ctx, replaceItemTags, itemID)
	return err
}

const tagNamesForItem = `-- name: TagNamesForItem :many
SELECT t.name FROM tags t
JOIN item_tags it ON it.tag_id = t.id
WHERE it.item_id = $1
ORDER BY t.name
`

func (q *Queries) TagNamesForItem(ctx context.Context, itemID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, tagNamesForItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkItemTag = `-- name: UnlinkItemTag :execrows
DELETE FROM item_tags WHERE item_id = $1 AND tag_id = $2
`

type UnlinkItemTagParams struct {
	ItemID int64
	TagID  int64
}

// remove_item_tag's underlying mutation — :execrows (not :exec) so the
// handler can report a clean "wasn't tagged with that" instead of a
// no-op success indistinguishable from an actual removal.
func (q *Queries) UnlinkItemTag(ctx context.Context, arg UnlinkItemTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkItemTag, arg.ItemID, arg.TagID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateItemFields = `-- name: UpdateItemFields :one
UPDATE items SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    quantity = COALESCE($3, quantity),
    condition = COALESCE($4, condition),
    purchase_date = COALESCE($5, purchase_date),
    purchase_price = COALESCE($6, purchase_price),
    receipt_url = COALESCE($7, receipt_url),
    updated_at = now()
WHERE id = $8
RETURNING id, storage_id, owner_id, is_shared, name, description, quantity, condition, qr_token, photo_url, purchase_date, purchase_price, receipt_url, custom_fields, created_at, updated_at
`

type UpdateItemFieldsParams struct {
	Name          *string
	Description   *string
	Quantity      *int32
	Condition     *string
	PurchaseDate  pgtype.Date
	PurchasePrice pgtype.Numeric
	ReceiptUrl    *string
	ID            int64
}

// MCP's edit_item tool. Storage moves go through move_item (its own audit
// trail), and tags through add_item_tag/remove_item_tag (additive, so a
// caller never needs to know an item's full existing tag list just to add
// one) — neither is a column this touches. COALESCE means a NULL arg
// leaves that column unchanged; same accepted "can't explicitly clear a
// nullable field back to NULL via this tool" limitation as
// UpdateStorageMetadata, for the same reason (no raw-JSON-map layer here to
// distinguish "absent" from "explicit null" the way REST's PATCH has).
func (q *Queries) UpdateItemFields(ctx context.Context, arg UpdateItemFieldsParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItemFields,
		arg.Name,
		arg.Description,
		arg.Quantity,
		arg.Condition,
		arg.PurchaseDate,
		arg.PurchasePrice,
		arg.ReceiptUrl,
		arg.ID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.StorageID,
		&i.OwnerID,
		&i.IsShared,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.Condition,
		&i.QrToken,
		&i.PhotoUrl,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.ReceiptUrl,
		&i.CustomFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateItemStorage = `-- name: UpdateItemStorage :execrows
UPDATE items SET storage_id = $1::bigint, updated_at = now()
WHERE id = $2::bigint
`

type UpdateItemStorageParams struct {
	StorageID int64
	ID        int64
}

// Backs the MCP move_item tool (§11) — a plain reassignment, paired with an
// InsertAuditLog call in the same handler (audit_log's first real writer;
// §3 defines the table but nothing has written to it before this tool).
// :execrows (not :exec) so move_item can tell a real reassignment apart
// from a no-op against an item deleted between resolveItem's lookup (on
// the pool, outside this transaction) and this UPDATE — without it, 0 rows
// affected still committed an audit_log "moved" row and reported success
// for a move that never happened.
func (q *Queries) UpdateItemStorage(ctx context.Context, arg UpdateItemStorageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateItemStorage, arg.StorageID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
