// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package store

import (
	"context"
)

const countDirectItemsAtLocation = `-- name: CountDirectItemsAtLocation :one

SELECT count(*) FROM items WHERE location_id = $1
`

// Location PATCH (rename, move, edit code, toggle is_shared — §9) is hand-written
// in internal/api/locations.go, not sqlc-generated: it accepts any subset of
// columns, including explicitly setting parent_id back to NULL, which a
// COALESCE-based static query can't distinguish from "not provided".
func (q *Queries) CountDirectItemsAtLocation(ctx context.Context, locationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDirectItemsAtLocation, locationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteItemsAtLocation = `-- name: DeleteItemsAtLocation :exec
DELETE FROM items WHERE location_id = $1
`

// Only used for the root-location force-delete case (§3) — a root location
// has no parent to promote its direct items to.
func (q *Queries) DeleteItemsAtLocation(ctx context.Context, locationID int64) error {
	_, err := q.db.Exec(ctx, deleteItemsAtLocation, locationID)
	return err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const descendantLocationIDs = `-- name: DescendantLocationIDs :many
WITH RECURSIVE descendants AS (
    SELECT l0.id, ARRAY[l0.id] AS visited FROM locations l0 WHERE l0.id = $1
    UNION ALL
    SELECT l.id, d.visited || l.id
    FROM locations l JOIN descendants d ON l.parent_id = d.id
    WHERE NOT (l.id = ANY(d.visited))
)
SELECT descendants.id FROM descendants
`

// Includes the root id itself, matching the mock's descendantLocationIds().
// Same visited-array cycle-detection insurance as LocationBreadcrumb above.
func (q *Queries) DescendantLocationIDs(ctx context.Context, id int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, descendantLocationIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, parent_id, owner_id, is_shared, name, qr_token, photo_url, notes, created_at FROM locations WHERE id = $1
`

func (q *Queries) GetLocationByID(ctx context.Context, id int64) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.OwnerID,
		&i.IsShared,
		&i.Name,
		&i.QrToken,
		&i.PhotoUrl,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getLocationsByParent = `-- name: GetLocationsByParent :many
SELECT id, parent_id, owner_id, is_shared, name, qr_token, photo_url, notes, created_at FROM locations WHERE parent_id IS NOT DISTINCT FROM $1 ORDER BY name
`

func (q *Queries) GetLocationsByParent(ctx context.Context, parentID *int64) ([]Location, error) {
	rows, err := q.db.Query(ctx, getLocationsByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.OwnerID,
			&i.IsShared,
			&i.Name,
			&i.QrToken,
			&i.PhotoUrl,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLocation = `-- name: InsertLocation :one
INSERT INTO locations (parent_id, owner_id, is_shared, name, qr_token, photo_url, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, parent_id, owner_id, is_shared, name, qr_token, photo_url, notes, created_at
`

type InsertLocationParams struct {
	ParentID *int64
	OwnerID  *int64
	IsShared bool
	Name     string
	QrToken  string
	PhotoUrl *string
	Notes    *string
}

func (q *Queries) InsertLocation(ctx context.Context, arg InsertLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, insertLocation,
		arg.ParentID,
		arg.OwnerID,
		arg.IsShared,
		arg.Name,
		arg.QrToken,
		arg.PhotoUrl,
		arg.Notes,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.OwnerID,
		&i.IsShared,
		&i.Name,
		&i.QrToken,
		&i.PhotoUrl,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const locationBreadcrumb = `-- name: LocationBreadcrumb :many
WITH RECURSIVE path AS (
    SELECT l0.id, l0.parent_id, l0.name, 1 AS depth, ARRAY[l0.id] AS visited
    FROM locations l0 WHERE l0.id = $1
    UNION ALL
    SELECT l.id, l.parent_id, l.name, p.depth + 1, p.visited || l.id
    FROM locations l JOIN path p ON l.id = p.parent_id
    WHERE NOT (l.id = ANY(p.visited))
)
SELECT path.id, path.name FROM path ORDER BY depth DESC
`

type LocationBreadcrumbRow struct {
	ID   int64
	Name string
}

// Root-to-leaf path (architecture plan §3). The `visited` array + the
// `WHERE NOT (l.id = ANY(p.visited))` guard is deliberate cycle-detection
// insurance: it's the only thing standing between a corrupted/cyclic
// parent_id chain and an infinite loop. Plain UNION (instead of UNION ALL)
// would NOT be enough here on its own — `depth` increments every iteration,
// so every row in a cycle is still a distinct tuple and UNION's dedup would
// never kick in. The real prevention is LocationsHandler.update rejecting a
// parent_id that would create a cycle in the first place
// (internal/api/locations.go) — this is just a backstop for rows that
// predate that check or were edited directly, and it bounds recursion to at
// most one pass over all locations regardless.
func (q *Queries) LocationBreadcrumb(ctx context.Context, id int64) ([]LocationBreadcrumbRow, error) {
	rows, err := q.db.Query(ctx, locationBreadcrumb, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocationBreadcrumbRow
	for rows.Next() {
		var i LocationBreadcrumbRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationExists = `-- name: LocationExists :one
SELECT EXISTS(SELECT 1 FROM locations WHERE id = $1)
`

func (q *Queries) LocationExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, locationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const locationQRTokenInUse = `-- name: LocationQRTokenInUse :one
SELECT EXISTS(
    SELECT 1 FROM locations
    WHERE TRANSLATE(UPPER(qr_token), 'OIL', '011') = TRANSLATE(UPPER($1::text), 'OIL', '011')
      AND id != $2::bigint
)
`

type LocationQRTokenInUseParams struct {
	QrToken string
	ID      int64
}

// Compared normalized (not raw), matching idx_locations_qr_token_normalized
// (migration 000002) — otherwise this pre-check could say "not in use" for a
// value the unique index would still reject. TRANSLATE(UPPER(x), ...), not
// UPPER(TRANSLATE(x, ...)) — see migration 000002's comment for why the
// order matters.
func (q *Queries) LocationQRTokenInUse(ctx context.Context, arg LocationQRTokenInUseParams) (bool, error) {
	row := q.db.QueryRow(ctx, locationQRTokenInUse, arg.QrToken, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const promoteItemsToParent = `-- name: PromoteItemsToParent :exec
UPDATE items SET location_id = $1::bigint
WHERE location_id = $2::bigint
`

type PromoteItemsToParentParams struct {
	NewLocationID int64
	OldLocationID int64
}

// Only valid when the location being deleted has a parent — moves its direct
// items up one level. Items nested inside child locations are unaffected;
// those child locations become root-level on their own via the FK's
// ON DELETE SET NULL when the DeleteLocation statement runs.
func (q *Queries) PromoteItemsToParent(ctx context.Context, arg PromoteItemsToParentParams) error {
	_, err := q.db.Exec(ctx, promoteItemsToParent, arg.NewLocationID, arg.OldLocationID)
	return err
}
