// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package store

import (
	"context"
)

const clearLocationFromStorages = `-- name: ClearLocationFromStorages :exec
UPDATE storages SET location_id = NULL WHERE location_id = $1
`

// Used by the force-delete path (§3-equivalent for locations): every
// storage assigned to a location being deleted becomes unassigned rather
// than the delete failing or cascading further.
func (q *Queries) ClearLocationFromStorages(ctx context.Context, locationID *int64) error {
	_, err := q.db.Exec(ctx, clearLocationFromStorages, locationID)
	return err
}

const countStoragesAtLocation = `-- name: CountStoragesAtLocation :one
SELECT count(*) FROM storages WHERE location_id = $1
`

func (q *Queries) CountStoragesAtLocation(ctx context.Context, locationID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countStoragesAtLocation, locationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const findLocationByName = `-- name: FindLocationByName :one
SELECT id, owner_id, is_shared, name, created_at FROM locations WHERE lower(name) = lower($1::text)
`

// Case-insensitive exact match, for MCP resolution — locations aren't in
// SearchSuggest (deliberately: no codes, a handful of rows, and adding them
// would crowd the shared top-10 the same way already fixed once for
// storages/items/tags — see CLAUDE.md).
func (q *Queries) FindLocationByName(ctx context.Context, name string) (Location, error) {
	row := q.db.QueryRow(ctx, findLocationByName, name)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsShared,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, owner_id, is_shared, name, created_at FROM locations WHERE id = $1
`

func (q *Queries) GetLocationByID(ctx context.Context, id int64) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsShared,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const insertLocation = `-- name: InsertLocation :one
INSERT INTO locations (owner_id, is_shared, name) VALUES ($1, $2, $3) RETURNING id, owner_id, is_shared, name, created_at
`

type InsertLocationParams struct {
	OwnerID  *int64
	IsShared bool
	Name     string
}

func (q *Queries) InsertLocation(ctx context.Context, arg InsertLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, insertLocation, arg.OwnerID, arg.IsShared, arg.Name)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsShared,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many

SELECT id, owner_id, is_shared, name, created_at FROM locations ORDER BY name
`

// Locations (architecture plan §3, added post-rename — see migration 000005)
// are a flat, non-nested physical-property entity: House, Garage, Parent's
// House. No recursion, no code/qr_token, no breadcrumb of their own — a
// storage's StorageBreadcrumb (storages.sql) picks up its assigned location
// (if any) by walking to its root ancestor.
func (q *Queries) ListLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.IsShared,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoragesAtLocation = `-- name: ListStoragesAtLocation :many
SELECT id, parent_id, owner_id, is_shared, name, qr_token, photo_url, notes, created_at, location_id FROM storages WHERE location_id = $1 ORDER BY name
`

func (q *Queries) ListStoragesAtLocation(ctx context.Context, locationID *int64) ([]Storage, error) {
	rows, err := q.db.Query(ctx, listStoragesAtLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Storage
	for rows.Next() {
		var i Storage
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.OwnerID,
			&i.IsShared,
			&i.Name,
			&i.QrToken,
			&i.PhotoUrl,
			&i.Notes,
			&i.CreatedAt,
			&i.LocationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationExists = `-- name: LocationExists :one
SELECT EXISTS(SELECT 1 FROM locations WHERE id = $1)
`

func (q *Queries) LocationExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, locationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateLocationName = `-- name: UpdateLocationName :one
UPDATE locations SET name = $2 WHERE id = $1 RETURNING id, owner_id, is_shared, name, created_at
`

type UpdateLocationNameParams struct {
	ID   int64
	Name string
}

// Static single-column update — unlike storages/items, a location has one
// editable field, so the dynamic-SET machinery those PATCH handlers need
// isn't warranted here.
func (q *Queries) UpdateLocationName(ctx context.Context, arg UpdateLocationNameParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocationName, arg.ID, arg.Name)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IsShared,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
