// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         int64
	EntityType string
	EntityID   int64
	Action     string
	UserID     *int64
	Details    []byte
	CreatedAt  pgtype.Timestamptz
}

type Item struct {
	ID            int64
	LocationID    int64
	OwnerID       *int64
	IsShared      bool
	Name          string
	Description   *string
	Quantity      int32
	Condition     *string
	QrToken       string
	PhotoUrl      *string
	PurchaseDate  pgtype.Date
	PurchasePrice pgtype.Numeric
	ReceiptUrl    *string
	CustomFields  []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ItemTag struct {
	ItemID int64
	TagID  int64
}

type Location struct {
	ID        int64
	ParentID  *int64
	OwnerID   *int64
	IsShared  bool
	Name      string
	QrToken   string
	PhotoUrl  *string
	Notes     *string
	CreatedAt pgtype.Timestamptz
}

type Tag struct {
	ID   int64
	Name string
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	Role         string
	CreatedAt    pgtype.Timestamptz
}
