// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findItemsByNormalizedCode = `-- name: FindItemsByNormalizedCode :many

SELECT i.id, i.location_id, i.owner_id, i.is_shared, i.name, i.description, i.quantity, i.condition, i.qr_token, i.photo_url, i.purchase_date, i.purchase_price, i.receipt_url, i.custom_fields, i.created_at, i.updated_at, COALESCE(array_agg(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL), '{}')::text[] AS tags
FROM items i
LEFT JOIN item_tags it ON it.item_id = i.id
LEFT JOIN tags t ON t.id = it.tag_id
WHERE TRANSLATE(UPPER(i.qr_token), 'OIL', '011') = TRANSLATE(UPPER($1::text), 'OIL', '011')
GROUP BY i.id
ORDER BY i.id
`

type FindItemsByNormalizedCodeRow struct {
	ID            int64
	LocationID    int64
	OwnerID       *int64
	IsShared      bool
	Name          string
	Description   *string
	Quantity      int32
	Condition     *string
	QrToken       string
	PhotoUrl      *string
	PurchaseDate  pgtype.Date
	PurchasePrice pgtype.Numeric
	ReceiptUrl    *string
	CustomFields  []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Tags          []string
}

// Exact-code lookups (§4/§6/§7) normalize the handful of common OCR/typing
// misreads before comparing — O→0, I/L→1, case-insensitive — the same way
// Crockford's own Base32 spec does, and the same way web/src/lib/api.ts's
// normalizeCode()/codesMatch() do for the mock. Always TRANSLATE(UPPER(x),
// ...), never UPPER(TRANSLATE(x, ...)) — TRANSLATE's match set ('OIL') is
// uppercase-only, so running it before UPPER() silently leaves a lowercase
// input's o/i/l untouched. (Caught late, via manual psql verification —
// UPPER(TRANSLATE('h4k9po','OIL','011')) comes back 'H4K9PO', not 'H4K9P0' —
// after this wrong order shipped once already: the random plain-text test
// codes never happened to contain a literal 0 or 1 for it to matter.)
func (q *Queries) FindItemsByNormalizedCode(ctx context.Context, code string) ([]FindItemsByNormalizedCodeRow, error) {
	rows, err := q.db.Query(ctx, findItemsByNormalizedCode, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindItemsByNormalizedCodeRow
	for rows.Next() {
		var i FindItemsByNormalizedCodeRow
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.OwnerID,
			&i.IsShared,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.Condition,
			&i.QrToken,
			&i.PhotoUrl,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.ReceiptUrl,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLocationByNormalizedCode = `-- name: FindLocationByNormalizedCode :one
SELECT id, parent_id, owner_id, is_shared, name, qr_token, photo_url, notes, created_at FROM locations
WHERE TRANSLATE(UPPER(qr_token), 'OIL', '011') = TRANSLATE(UPPER($1::text), 'OIL', '011')
`

func (q *Queries) FindLocationByNormalizedCode(ctx context.Context, code string) (Location, error) {
	row := q.db.QueryRow(ctx, findLocationByNormalizedCode, code)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.OwnerID,
		&i.IsShared,
		&i.Name,
		&i.QrToken,
		&i.PhotoUrl,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getItemLocationID = `-- name: GetItemLocationID :one
SELECT location_id FROM items WHERE id = $1
`

func (q *Queries) GetItemLocationID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getItemLocationID, id)
	var location_id int64
	err := row.Scan(&location_id)
	return location_id, err
}

const searchSuggest = `-- name: SearchSuggest :many
WITH matches AS (
    (
        SELECT 'item'::text AS kind, i.id, i.name, 1.0::real AS score
        FROM items i
        WHERE TRANSLATE(UPPER(i.qr_token), 'OIL', '011') = TRANSLATE(UPPER($1::text), 'OIL', '011')
    )
    UNION ALL
    (
        SELECT 'location'::text AS kind, l.id, l.name, 1.0::real AS score
        FROM locations l
        WHERE TRANSLATE(UPPER(l.qr_token), 'OIL', '011') = TRANSLATE(UPPER($1::text), 'OIL', '011')
    )
    UNION ALL
    (
        SELECT 'item'::text AS kind, i.id, i.name, similarity(i.name, $1::text) AS score
        FROM items i
        WHERE i.name ILIKE $1::text || '%' OR i.name % $1::text
    )
    UNION ALL
    (
        SELECT 'location'::text AS kind, l.id, l.name, similarity(l.name, $1::text) AS score
        FROM locations l
        WHERE l.name ILIKE $1::text || '%' OR l.name % $1::text
    )
    UNION ALL
    (
        SELECT 'tag'::text AS kind, tg.id, tg.name, similarity(tg.name, $1::text) AS score
        FROM tags tg
        WHERE tg.name ILIKE $1::text || '%' OR tg.name % $1::text
    )
),
deduped AS (
    SELECT DISTINCT ON (kind, id) kind, id, name, score
    FROM matches
    ORDER BY kind, id, score DESC
)
SELECT kind, id, name, score FROM deduped
ORDER BY score DESC, name
LIMIT 10
`

type SearchSuggestRow struct {
	Kind  string
	ID    int64
	Name  string
	Score float32
}

// Unified autocomplete (§5): exact (normalized) code matches score 1.0 and
// always sort first; everything else is pg_trgm similarity/prefix matching.
// Deduped by (kind, id) keeping the higher score before the final sort —
// a query can hit both an entity's code and its name (e.g. typing part of a
// location's own plain-text code that also happens to prefix-match a name),
// and without the dedup step that entity would appear twice.
// location_id deliberately isn't selected here even for item hits — mixing
// a real bigint (items) with a literal NULL (locations/tags) in one UNION
// confused sqlc's static nullability inference into emitting a non-nullable
// int64 field that would fail to scan a real NULL row at runtime. Callers
// fetch each item hit's location_id + breadcrumb with GetItemLocationID
// below instead — a handful of extra tiny queries per search, fine at this
// app's scale, and it sidesteps the inference problem entirely.
func (q *Queries) SearchSuggest(ctx context.Context, query string) ([]SearchSuggestRow, error) {
	rows, err := q.db.Query(ctx, searchSuggest, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSuggestRow
	for rows.Next() {
		var i SearchSuggestRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.Name,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
