// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storages.sql

package store

import (
	"context"
)

const countDirectItemsAtStorage = `-- name: CountDirectItemsAtStorage :one

SELECT count(*) FROM items WHERE storage_id = $1
`

// Storage PATCH (rename, move, edit code, toggle is_shared — §9) is hand-written
// in internal/api/storages.go, not sqlc-generated: it accepts any subset of
// columns, including explicitly setting parent_id back to NULL, which a
// COALESCE-based static query can't distinguish from "not provided".
func (q *Queries) CountDirectItemsAtStorage(ctx context.Context, storageID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDirectItemsAtStorage, storageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteItemsAtStorage = `-- name: DeleteItemsAtStorage :exec
DELETE FROM items WHERE storage_id = $1
`

// Only used for the root-storage force-delete case (§3) — a root storage
// has no parent to promote its direct items to.
func (q *Queries) DeleteItemsAtStorage(ctx context.Context, storageID int64) error {
	_, err := q.db.Exec(ctx, deleteItemsAtStorage, storageID)
	return err
}

const deleteStorage = `-- name: DeleteStorage :exec
DELETE FROM storages WHERE id = $1
`

func (q *Queries) DeleteStorage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteStorage, id)
	return err
}

const descendantStorageIDs = `-- name: DescendantStorageIDs :many
WITH RECURSIVE descendants AS (
    SELECT s0.id, ARRAY[s0.id] AS visited FROM storages s0 WHERE s0.id = $1
    UNION ALL
    SELECT s.id, d.visited || s.id
    FROM storages s JOIN descendants d ON s.parent_id = d.id
    WHERE NOT (s.id = ANY(d.visited))
)
SELECT descendants.id FROM descendants
`

// Includes the root id itself. Same visited-array cycle-detection insurance
// as StorageBreadcrumb above.
func (q *Queries) DescendantStorageIDs(ctx context.Context, id int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, descendantStorageIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStorageByID = `-- name: GetStorageByID :one
SELECT id, parent_id, owner_id, is_shared, name, qr_token, photo_url, notes, created_at FROM storages WHERE id = $1
`

func (q *Queries) GetStorageByID(ctx context.Context, id int64) (Storage, error) {
	row := q.db.QueryRow(ctx, getStorageByID, id)
	var i Storage
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.OwnerID,
		&i.IsShared,
		&i.Name,
		&i.QrToken,
		&i.PhotoUrl,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getStoragesByParent = `-- name: GetStoragesByParent :many
SELECT id, parent_id, owner_id, is_shared, name, qr_token, photo_url, notes, created_at FROM storages WHERE parent_id IS NOT DISTINCT FROM $1 ORDER BY name
`

func (q *Queries) GetStoragesByParent(ctx context.Context, parentID *int64) ([]Storage, error) {
	rows, err := q.db.Query(ctx, getStoragesByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Storage
	for rows.Next() {
		var i Storage
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.OwnerID,
			&i.IsShared,
			&i.Name,
			&i.QrToken,
			&i.PhotoUrl,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertStorage = `-- name: InsertStorage :one
INSERT INTO storages (parent_id, owner_id, is_shared, name, qr_token, photo_url, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, parent_id, owner_id, is_shared, name, qr_token, photo_url, notes, created_at
`

type InsertStorageParams struct {
	ParentID *int64
	OwnerID  *int64
	IsShared bool
	Name     string
	QrToken  string
	PhotoUrl *string
	Notes    *string
}

func (q *Queries) InsertStorage(ctx context.Context, arg InsertStorageParams) (Storage, error) {
	row := q.db.QueryRow(ctx, insertStorage,
		arg.ParentID,
		arg.OwnerID,
		arg.IsShared,
		arg.Name,
		arg.QrToken,
		arg.PhotoUrl,
		arg.Notes,
	)
	var i Storage
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.OwnerID,
		&i.IsShared,
		&i.Name,
		&i.QrToken,
		&i.PhotoUrl,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const promoteItemsToParent = `-- name: PromoteItemsToParent :exec
UPDATE items SET storage_id = $1::bigint
WHERE storage_id = $2::bigint
`

type PromoteItemsToParentParams struct {
	NewStorageID int64
	OldStorageID int64
}

// Only valid when the storage being deleted has a parent — moves its direct
// items up one level. Items nested inside child storages are unaffected;
// those child storages become root-level on their own via the FK's
// ON DELETE SET NULL when the DeleteStorage statement runs.
func (q *Queries) PromoteItemsToParent(ctx context.Context, arg PromoteItemsToParentParams) error {
	_, err := q.db.Exec(ctx, promoteItemsToParent, arg.NewStorageID, arg.OldStorageID)
	return err
}

const storageBreadcrumb = `-- name: StorageBreadcrumb :many
WITH RECURSIVE path AS (
    SELECT s0.id, s0.parent_id, s0.name, 1 AS depth, ARRAY[s0.id] AS visited
    FROM storages s0 WHERE s0.id = $1
    UNION ALL
    SELECT s.id, s.parent_id, s.name, p.depth + 1, p.visited || s.id
    FROM storages s JOIN path p ON s.id = p.parent_id
    WHERE NOT (s.id = ANY(p.visited))
)
SELECT path.id, path.name FROM path ORDER BY depth DESC
`

type StorageBreadcrumbRow struct {
	ID   int64
	Name string
}

// Root-to-leaf path (architecture plan §3). The `visited` array + the
// `WHERE NOT (s.id = ANY(p.visited))` guard is deliberate cycle-detection
// insurance: it's the only thing standing between a corrupted/cyclic
// parent_id chain and an infinite loop. Plain UNION (instead of UNION ALL)
// would NOT be enough here on its own — `depth` increments every iteration,
// so every row in a cycle is still a distinct tuple and UNION's dedup would
// never kick in. The real prevention is StoragesHandler.update rejecting a
// parent_id that would create a cycle in the first place
// (internal/api/storages.go) — this is just a backstop for rows that
// predate that check or were edited directly, and it bounds recursion to at
// most one pass over all storages regardless.
func (q *Queries) StorageBreadcrumb(ctx context.Context, id int64) ([]StorageBreadcrumbRow, error) {
	rows, err := q.db.Query(ctx, storageBreadcrumb, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageBreadcrumbRow
	for rows.Next() {
		var i StorageBreadcrumbRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storageExists = `-- name: StorageExists :one
SELECT EXISTS(SELECT 1 FROM storages WHERE id = $1)
`

func (q *Queries) StorageExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, storageExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const storageQRTokenInUse = `-- name: StorageQRTokenInUse :one
SELECT EXISTS(
    SELECT 1 FROM storages
    WHERE TRANSLATE(UPPER(qr_token), 'OIL', '011') = TRANSLATE(UPPER($1::text), 'OIL', '011')
      AND id != $2::bigint
)
`

type StorageQRTokenInUseParams struct {
	QrToken string
	ID      int64
}

// Compared normalized (not raw), matching idx_storages_qr_token_normalized
// (migration 000002) — otherwise this pre-check could say "not in use" for a
// value the unique index would still reject. TRANSLATE(UPPER(x), ...), not
// UPPER(TRANSLATE(x, ...)) — see migration 000002's comment for why the
// order matters.
func (q *Queries) StorageQRTokenInUse(ctx context.Context, arg StorageQRTokenInUseParams) (bool, error) {
	row := q.db.QueryRow(ctx, storageQRTokenInUse, arg.QrToken, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
